# Generated by Django 5.0.6 on 2024-07-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="cash_balance",
            field=models.FloatField(default=0.0),
        ),
    ]
