# Generated by Django 5.0.6 on 2024-07-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_investment_sale_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="investment",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="investment",
            name="sale_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
